;织网者默认资源
[Info]
Name=新增国家
DescShort=用这个模块可以简单新增国家
DescLong=

[Register]
****Injector=Injector
****=Register
****Side=Register
****InjectorAI=Injector

[****Country]
UIName=
Name=
Suffix=Soviet
Prefix=B
Color=DarkRed
Multiplay=yes
Side=****Side
SmartAI=yes
AI.PowerPlants=
RandomSelectionWeight=0 
File.Flag=
File.LoadScreen=
File.LoadScreenPAL=
LoadScreenText.Name=
LoadScreenText.SpecialName=
LoadScreenText.Brief=

[****Injector]
DisplayName#Prop = 注入器
SkipExport#Var = true
#InjectInto=Sides
****Side=****Country

[****InjectorAI]
DisplayName#Prop = 注入器
SkipExport#Var = true
#InjectInto=AI
BuildConst=
BuildPower=
BuildRefinery=
BuildBarracks=
BuildTech=
BuildWeapons=
BuildRadar=
ConcreteWalls=
NSGates=
EWGates=
BuildNavalYard=
BuildDummy=

[****Side]
DefaultDisguise=
Crew=
Engineer=
SurvivorDivisor=450 ;建筑价格除以这个数决定残兵的数量
AI.BaseDefenses=
AI.BaseDefenseCounts=30,25
ParaDrop.Types=
ParaDrop.Num=8
Sidebar.MixFileIndex=2
EVA.Tag=

