[Info]
Name=Vector圆面旋转
DescShort=Vector圆面法向量旋转
DescLong=记得设置高度偏移。设置后圆面会每帧转动

[Register]
****=FlagPack

[****]
#Vector.NormalFAnglePerStep=3
#Vector.NormalLAnglePerStep=3
#Vector.NormalHAnglePerStep=3

Vector.IsNormalOnOrigin=yes
Vector.NormalIsOnTurret=no








