;可以在INI文件中很简单的使用文本搜索来快速找到你所需要的对象
[Name:E1]				=		美国大兵
[Name:SNIPE]			=		狙击手
[Name:FLAKT]			=		防空步兵
[Name:E2]				=		动员兵
[Name:SHK]				=		磁爆步兵
[Name:ENGINEER]			=		工程师
[Name:JUMPJET]			=		火箭飞行兵
[Name:GHOST]			=		海豹部队
[Name:TANYA]			=		谭雅
[Name:YURI]				=		尤里
[Name:IVAN]				=		疯狂伊万
[Name:DESO]				=		辐射工兵
[Name:CLEG]				=		超时空军团兵
[Name:DOG]				=		军犬
[Name:CIV1]				=		平民
[Name:CIV2]				=		平民
[Name:CIV3]				=		平民
[Name:COW]				=		乳牛
[Name:CTECH]			=		技师
[Name:WEEDGUY]			=		化学兵
[Name:SPY]				=		间谍
[Name:TERROR]			=		恐怖份子
[Name:CCOMAND]			=		超时空突击队
[Name:PTROOP]			=		超能力部队
[Name:CIVAN]			=		超时空伊万
[Name:YURIPR]			=		尤里改
[Name:HVR]				=		盘旋猴
[Name:APOC]				=		天启坦克
[Name:DTRUCK]			=		自爆卡车
[Name:TRUCKA]			=		卡车
[Name:TRUCKB]			=		卡车（载货）
[Name:SUB]				=		颱风级攻击潜艇
[Name:DLPH]				=		海豚
[Name:AEGIS]			=		神盾巡洋舰
[Name:CARRIER]			=		航空母舰
[Name:CARRIERB]			=		尼米兹号航空母舰
[Name:DRED]				=		无畏级战舰
[Name:DREDB]			=		无畏级战舰+3
[Name:HYD]				=		海蝎
[Name:DEST]				=		驱逐舰
[Name:V3]				=		V3火箭发射车
[Name:DRON]				=		恐怖机器人
[Name:SQD]				=		巨型乌贼
[Name:HORV]				=		武装采矿车
[Name:HARV]				=		武装采矿车
[Name:CMON]				=		超时空采矿车（未装载）
[Name:CMIN]				=		超时空采矿车
[Name:AMCV]				=		盟军机动基地车
[Name:SMCV]				=		苏联机动基地车
[Name:LCRF]				=		两栖运输艇
[Name:HTK]				=		防空履带车
[Name:BUS]				=		校车
[Name:LOCOMOTIVE]		=		火车
[Name:TRAINCAR]			=		教练车
[Name:CARGOCAR]			=		运输车
[Name:PICK]				=		小货车
[Name:CAR]				=		汽车
[Name:WINI]				=		休旅车
[Name:HTNK]				=		犀牛坦克
[Name:LTNK]				=		轻坦克
[Name:MTNK]				=		灰熊坦克
[Name:MGTK]				=		幻影坦克
[Name:FV]				=		多功能步兵战斗车
[Name:TNKD]				=		坦克杀手
[Name:HOWI]				=		榴弹炮
[Name:SAPC]				=		装甲运兵船
[Name:TTNK]				=		磁能坦克
[Name:SREF]				=		光稜坦克
[Name:XCOMET]			=		位置标定器
[Name:ORCA]				=		入侵者战机
[Name:BEAGLE]			=		黑鹰战机
[Name:ORCATRAN]			=		黑鸥运输机损坏版
[Name:HIND]				=		雌鹿运输直升机
[Name:TRNSPORT]			=		运输机
[Name:SHAD]				=		夜鹰直升机
[Name:ZEP]				=		基洛夫空艇
[Name:HORNET]			=		黄蜂
[Name:DMISL]			=		飞弹
[Name:ASW]				=		鹗式运输机
[Name:V3ROCKET]			=		V3火箭
[Name:APACHE]			=		阿帕契
[Name:PDPLANE]			=		运输机
[Name:GATECH]			=		盟军作战实验室
[Name:GAWEAP]			=		盟军战车工厂
[Name:NAWEAP]			=		苏联战车工厂
[Name:GACNST]			=		盟军建造场
[Name:NACNST]			=		苏联建造场
[Name:GADPSA]			=		已部署之侦测阵列
[Name:GAICBM]			=		已部署之洲际弹道飞弹
[Name:GATICK]			=		已部署之坦克
[Name:GAARTY]			=		已部署之野炮
[Name:GAREFN]			=		盟军矿石精炼厂
[Name:NAREFN]			=		苏联矿石精炼厂
[Name:GASILO]			=		储存槽
[Name:GAYARD]			=		盟军造船厂
[Name:NAYARD]			=		苏联船坞
[Name:GAAIRC]			=		空指部
[Name:GAHPAD]			=		机场
[Name:NAHPAD]			=		直升机场
[Name:GARADR]			=		指挥中心
[Name:GASPYSAT]			=		间谍卫星
[Name:GAGAP]			=		裂缝产生器
[Name:NASTLH]			=		匿踪产生器
[Name:GAPOWR]			=		发电厂
[Name:NAPOWR]			=		磁能反应炉
[Name:NAAPWR]			=		先进发电厂
[Name:NATECH]			=		苏联作战实验室
[Name:NAHAND]			=		苏联兵营
[Name:GAOREP]			=		矿石精炼器
[Name:NACLON]			=		复制中心
[Name:GAPILE]			=		盟军兵营
[Name:GADEPT]			=		盟军维修厂
[Name:GAPAVE]			=		道路
[Name:GAGREEN]			=		环保建筑
[Name:GASAND]			=		沙袋
[Name:GAWALL]			=		盟军围墙
[Name:GAFWLL]			=		法国围墙
[Name:NAWALL]			=		苏联围墙
[Name:CABHUT]			=		桥梁维修小屋
[Name:NAPULS]			=		电磁炮
[Name:GACTWR]			=		组合塔
[Name:GAKODK]			=		大熊
[Name:NAIRON]			=		铁幕装置
[Name:GAWEAT]			=		天气控制机
[Name:GACSPH]			=		超时空传送仪
[Name:GADUMY]			=		超时空传送仪
[Name:NARADR]			=		雷达
[Name:NAPSIS]			=		心灵探测器
[Name:NAWAST]			=		废弃物处理设施
[Name:TESLA]			=		磁爆线圈
[Name:ATESLA]			=		光稜塔
[Name:NAMISL]			=		核弹发射井
[Name:GAVULC]			=		巴尔干炮
[Name:GAROCK]			=		RPG升级
[Name:GACSAM]			=		地对空飞弹升级
[Name:GAPOWRUP]			=		动力涡轮
[Name:GAPLUG1]			=		威胁等级节点
[Name:GAPLUG2]			=		搜寻者控制
[Name:GAPLUG3]			=		离子炮连结
[Name:GAFIRE]			=		火风暴产生器
[Name:NAPOST]			=		雷射防护站
[Name:NAFNCE]			=		雷射防护部队
[Name:NALASR]			=		哨戒炮
[Name:GAPILL]			=		机枪碉堡
[Name:NASAM]			=		爱国者飞弹
[Name:GAFSDF]			=		火风暴围墙
[Name:ABAN01]			=		西木原木公司
[Name:ABAN02]			=		帕奴洛大牧场
[Name:ABAN03]			=		废弃工厂
[Name:ABAN04]			=		市政府
[Name:ABAN05]			=		狩猎小屋
[Name:ABAN06]			=		地方旅馆
[Name:ABAN07]			=		教堂
[Name:ABAN08]			=		废弃仓库
[Name:ABAN09]			=		托尔的住所
[Name:ABAN10]			=		汽车旅馆
[Name:ABAN11]			=		米利庄园
[Name:ABAN12]			=		凯特勒寓所
[Name:ABAN13]			=		隆格之家
[Name:ABAN14]			=		地方商店
[Name:ABAN15]			=		亚当之家
[Name:ABAN16]			=		加油站
[Name:ABAN17]			=		加油帮浦
[Name:ABAN18]			=		加油站招牌
[Name:CA0001]			=		雷得旅馆
[Name:CA0002]			=		山伯父子之家
[Name:CA0003]			=		临时住宅
[Name:CA0004]			=		小站
[Name:CA0005]			=		出售小屋
[Name:CA0006]			=		豪华旅馆
[Name:CA0007]			=		力场产生器
[Name:CA0008]			=		地下住宅
[Name:CA0009]			=		地下住宅
[Name:CA0010]			=		李利旅人之家
[Name:CA0011]			=		水槽
[Name:CA0012]			=		温室
[Name:CA0013]			=		净水厂
[Name:CA0014]			=		观测塔
[Name:CA0015]			=		港口小木屋
[Name:CA0016]			=		豪华港口小木屋
[Name:CA0017]			=		能量转换器
[Name:CA0018]			=		太阳能电池板
[Name:CA0019]			=		太阳能电池板
[Name:CA0020]			=		太阳能电池板
[Name:CA0021]			=		太阳能电池板
[Name:GAOLDCC1]			=		旧建造厂
[Name:GAOLDCC2]			=		旧神殿
[Name:GAOLDCC3]			=		旧武器工厂
[Name:GAOLDCC4]			=		旧精炼厂
[Name:GAOLDCC5]			=		旧先进发电厂
[Name:GAOLDCC6]			=		旧贮槽
[Name:CAOUTP]			=		科技前哨站
[Name:CATHOSP]			=		科技医院
[Name:CAHOSP]			=		市民医院
[Name:CAAIRP]			=		科技机场
[Name:CAOILD]			=		科技钻油井
[Name:CAARMR]			=		国民兵训练中心
[Name:CAPYR01]			=		金字塔
[Name:CAPYR02]			=		金字塔
[Name:CAPYR03]			=		金字塔
[Name:CAARAY]			=		市民群
[Name:GASPOT]			=		灯塔
[Name:CITY01]			=		法院部门
[Name:CITY02]			=		莱特纳豪华傢俱
[Name:CITY03]			=		办公大楼
[Name:CITY04]			=		WESTWOOD股市交易所
[Name:CITY05]			=		太阳日报
[Name:CITY06]			=		优卡可乐公司
[Name:CITY07]			=		都市住宅
[Name:CITY08]			=		伊斯折扣酒吧
[Name:CITY09]			=		废弃仓库
[Name:CITY10]			=		都市店面
[Name:CITY11]			=		候机室
[Name:CITY12]			=		波士底大厦
[Name:CITY13]			=		修维美髮沙龙
[Name:CITY14]			=		商业办公室
[Name:CITY15]			=		第二国家银行
[Name:CITY16]			=		超高层饭店
[Name:CITY17]			=		国民住宅
[Name:CITY18]			=		射手收容所
[Name:CITY19]			=		斐乐抽水站
[Name:CITY20]			=		加油帮浦
[Name:CITY21]			=		加油站招牌
[Name:CITY22]			=		教堂
[Name:CTVEGA]			=		织女星金字塔
[Name:BBOARD01]			=		来雷德旅馆
[Name:BBOARD02]			=		美味的优卡可乐！
[Name:BBOARD03]			=		汉堡$99
[Name:BBOARD04]			=		拉斯维加斯观光
[Name:BBOARD05]			=		房间每晚$29
[Name:BBOARD06]			=		军事仓库
[Name:BBOARD07]			=		硷电池大型商场
[Name:BBOARD08]			=		鳄鱼王宠物店就在前头！
[Name:BBOARD09]			=		战术高手舞厅！
[Name:BBOARD10]			=		WW海鲜牛排餐，来试试吧！
[Name:BBOARD11]			=		离迪库咖啡厅仅十一哩！
[Name:BBOARD12]			=		没有人可以从射手收容所逃脱！
[Name:BBOARD13]			=		来修维美髮沙龙坐坐吧
[Name:BBOARD14]			=		比尔鲍伯收割机学校
[Name:BBOARD15]			=		潘奴洛大庄园
[Name:CTDAM]			=		水库
[Name:CAPARS01]			=		艾菲尔铁塔
[Name:CACITY01]			=		建筑物
[Name:CACITY02]			=		建筑物
[Name:CACITY03]			=		建筑物
[Name:CACITY04]			=		建筑物
[Name:CANEWY01]			=		建筑物
[Name:CANEWY04]			=		自由女神像
[Name:CANEWY05]			=		世界贸易中心
[Name:CASWST01]			=		建筑物
[Name:CATECH01]			=		通讯中心
[Name:CATEXS01]			=		建筑物
[Name:CATEXS02]			=		白杨木屋
[Name:CAWASH01]			=		白宫
[Name:CAFARM01]			=		农庄
[Name:CAFARM02]			=		农庄贮槽
[Name:CALIT01E]			=		照明设施
[Name:CALIT01N]			=		照明设施
[Name:CALIT01S]			=		照明设施
[Name:CALIT01W]			=		照明设施
[Name:CAMISC01]			=		油桶
[Name:CAMISC02]			=		油桶
[Name:CAMISC03]			=		子母垃圾车
[Name:CAMISC04]			=		邮筒
[Name:CAPOL01E]			=		电话线杆
[Name:CAPOL01N]			=		电话线杆
[Name:CAPOL01S]			=		电话线杆
[Name:CAPOL01W]			=		电话线杆
[Name:AMMOCRAT]			=		弹药箱
[Name:GTGCAN]			=		巨炮
[Name:NANRCT]			=		核子反应炉
[Name:NAFLAK]			=		防空炮
[Name:CAWSH12]			=		华盛顿纪念碑
[Name:NUKE]				=		核弹攻击
[Name:ION]				=		离子炮
[Name:IRON]				=		铁幕装置
[Name:STORM]			=		闪电风暴
[Name:CHRONO]			=		超时空传送
[Name:CHRONO2]			=		超时空发动二
[Name:PARA]				=		伞兵
[Name:ALLIGATOR]		=		鳄鱼
[Name:NADEPT]			=		苏联维修工厂　
[Name:CAWASH12]			=		华盛顿纪念碑
[Name:CAEUR1]			=		小屋
[Name:CAEUR2]			=		小屋2
[Name:CAMIAM02]			=		饭店
[Name:CAPRS03]			=		世界惊奇博物馆
[Name:CAMEX01]			=		马雅金字塔
[Name:MAYAN]			=		马雅金字塔2
[Name:CARUS03]			=		克里姆林宫　
[Name:CAPRS07]			=		电话亭
[Name:CAWASH15]			=		林肯纪念馆
[Name:CAGAS01]			=		加油站
[Name:CAPARS11]			=		巴黎凯旋门
[Name:CAPARS12]			=		大教堂
[Name:CAFARM06]			=		灯塔
[Name:CAMIAM04]			=		救生员休息亭
[Name:NAPSYB]			=		心灵信标
[Name:NAPSYA]			=		心灵控制增幅器
[Name:CAIND01]			=		工厂
[Name:CACOLO01]			=		空军学院礼拜堂
[Name:CACHIG04]			=		芝加哥协会大楼
[Name:CAMIAM03]			=		饭店
[Name:CAMIAM01]			=		饭店2
[Name:CARUS07]			=		红场
[Name:CATEXS06]			=		办公大楼1
[Name:CATEXS07]			=		办公大楼2　
[Name:CATEXS08]			=		办公大楼3
[Name:CAWASH16]			=		史密索尼安城堡
[Name:CAWASH17]			=		自然历史博物馆
[Name:CACHIG05]			=		席尔斯大楼
[Name:CAWASH19]			=		胜利纪念碑
[Name:CANEWY20]			=		仓库
[Name:CAMSC01]			=		美又美热狗摊！　
[Name:CAMSC02]			=		遮阳伞
[Name:CAMSC04]			=		海滩毛巾
[Name:CAMSC06]			=		营火
[Name:CAMSC07]			=		小屋
[Name:CAWASH18]			=		喷水池
[Name:CAEURO05]			=		雕像
[Name:CAPARK01]			=		公园长椅
[Name:CAPARK02]			=		秋千
[Name:CAPARK03]			=		旋转盘
[Name:CASTL04]			=		拱门　
[Name:CAHSE05]			=		货柜屋
[Name:CAHSE06]			=		货柜屋
[Name:CAARMY01]			=		军队营帐
[Name:CAUSFGL]			=		美国国旗
[Name:CAGARD01]			=		警卫哨
[Name:CARUS01]			=		圣巴索大教堂
[Name:CAFRMA]			=		农舍
[Name:CAFRMB]			=		移动式厕所
[Name:CAHSE01]			=		房屋
[Name:CAWT01]			=		水塔
[Name:CATS01]			=		谷仓
[Name:CABARN02]			=		谷仓
[Name:CAWA2A]			=		五角大厦
[Name:CONA]				=		挖土机
[Name:CAWSH14]			=		杰佛逊纪念馆
[Name:VLADBOAT]			=		维拉迪摩指挥舰
[Name:PIGCAR]			=		警车
[Name:PRES]				=		总统
[Name:CAMISC06]			=		V3飞弹
[Name:TAXI]				=		计程车
[Name:CRUISESHIP]		=		游轮
[Name:PROPA]			=		宣传车
[Name:LIMO]				=		豪华轿车
[Name:CDEST]			=		海岸巡防艇
[Name:TUGBOAT]			=		拖船
[Name:GATE1]			=		闸门
[Name:CAMIAM08]			=		亚历桑那纪念馆
[Name:CAMISC12]			=		练习靶
[Name:CAMISC13]			=		废弃坦克
[Name:CASTL05]			=		体育馆
[Name:CUBANFLAG]		=		古巴国旗
[Name:RUSSIANFLAG]		=		俄国国旗
[Name:FRENCHFLAG]		=		法国国旗
[Name:IRAQFLAG]			=		伊拉克国旗
[Name:KOREAFLAG]		=		韩国国旗
[Name:LYBIAFLAG]		=		利比亚国旗
[Name:GERMANFLAG]		=		德国国旗
[Name:UKFLAG]			=		英国国旗
[Name:POLISHFLAG]		=		波兰国旗
[Name:MAYANRUINS]		=		马雅遗迹
[Name:MAYANTEMPLE]		=		马雅神殿
[Name:CAMISC05]			=		水管
[Name:CAMISC11]			=		轮胎
[Name:CAMSC10]			=		牛肉堡王
[Name:SECRETSERVICE]	=		终极保镖
[Name:EINSTEINLAB]		=		爱因斯坦实验室
[Name:CABANA]			=		海滨酒吧
[Name:PCOMMANDO]		=		心灵突击队
[Name:POLARBEAR]		=		南极熊
[Name:MONKEY]			=		猴子
[Name:CAMOV01]			=		广告看板
[Name:CAMOV02]			=		停车场商店
[Name:CABUNK01]			=		燃料库
[Name:INIT]				=		尤里新兵
[Name:Virus]			=		病毒狙击手
[Name:BRUTE]			=		狂兽人
[Name:YURICLONE]		=		尤里复制人
[Name:YURIPRIME]		=		尤里X
[Name:LASHER]			=		狂风坦克
[Name:GATTTANK]			=		盖特机炮坦克
[Name:CHAOSDRONE]		=		神经突击车
[Name:MASTERMIND]		=		精神控制车
[Name:MAGNETRON]		=		磁电坦克
[Name:YMCV]				=		尤里机动基地车
[Name:BOOMER]			=		雷鸣攻击潜舰
[Name:BIOR]				=		生化反应炉
[Name:YBARRACKS]		=		尤里兵营
[Name:YWARFACTORY]		=		尤里战车工厂
[Name:GRINDER]			=		部队回收厂
[Name:YBLAB]			=		尤里作战实验室
[Name:YNAVAL]			=		尤里海军船坞
[Name:YAPSYT]			=		心灵控制塔
[Name:GATTCANNON]		=		盖特机炮
[Name:CITADEL]			=		护城墙
[Name:YAPPET]			=		心灵控制器
[Name:BATTLEFORTRESS]	=		战斗要塞
[Name:GUARDIANGI]		=		重装大兵
[Name:SIEGECHOPPER]		=		武装直升机
[Name:BORIS]			=		鲍里斯
[Name:INDUSTRIALPLANT]	=		工业工厂
[Name:NATBNK]			=		坦克碉堡
[Name:NABNKR]			=		战斗碉堡
[Name:CASLAB]			=		秘密科技实验室
[Name:DISK]				=		雷射幽浮
[Name:SMIN]				=		奴隶矿场
[Name:SLAV]				=		奴隶
[Name:YACNST]			=		尤里建造场
[Name:ROBOTANK]			=		遥控坦克
[Name:ROBOCONT]			=		控制中心
[Name:FORCESHIELD]		=		力场护盾
[Name:SPYP]				=		侦察机
[Name:CAML]				=		骆驼
[Name:EINS]				=		爱因斯坦
[Name:DNOA]				=		暴龙
[Name:CLNT]				=		牛仔
[Name:RMNV]				=		洛马诺夫总理
[Name:MUMY]				=		木乃伊
[Name:STLN]				=		蓝波
[Name:ARND]				=		魔鬼终结者
[Name:CAEGYP03]			=		人面狮身像
[Name:CALA01]			=		小型购物中心
[Name:CALA09]			=		便利商店
[Name:CALOND04]			=		英国国会
[Name:CALOND06]			=		伦敦塔
[Name:CALOND05]			=		大笨钟
[Name:CAMORR05]			=		理克酒馆
[Name:CASANF05]			=		恶魔岛
[Name:CASANF04]			=		金门大桥
[Name:CASANF15]			=		恶魔岛水塔
[Name:CASEAT02]			=		巨软园区
[Name:CASYDN03]			=		雪梨歌剧院
[Name:CAEAST01]			=		复活岛石像
[Name:CAEAST02]			=		尤里雕像
[Name:CATRAN03]			=		尤里要塞
[Name:CALA03]			=		好莱坞标志
[Name:CALA04]			=		好莱坞剧场
[Name:CALA05]			=		洛杉矶
[Name:CALA06]			=		洛杉矶塔台
[Name:CALA08]			=		汽车代理商
[Name:CASEAT01]			=		西雅图太空针塔
[Name:CASYDN02]			=		麦克鲁汉堡
[Name:CATRAN01]			=		地窖
[Name:LUNR]				=		登月火箭员
[Name:CAMACH]			=		科技机器商店
[Name:BLACKCAB]			=		黑色计程车
[Name:YCAB]				=		黄色计程车
[Name:DOLY]				=		摄影车
[Name:CBLC]				=		电车
[Name:FTRK]				=		救火车
[Name:AMBU]				=		救护车
[Name:CALA07]			=		电影院
[Name:YAROCK]			=		不明建筑物
[Name:YURIRAD]			=		心灵感应器
[Name:CALA10]			=		看板
[Name:CAURB03]			=		聚光灯
[Name:CASTRT05]			=		公车站
[Name:CABARR]			=		拒马
[Name:CASIN03]			=		施工标志
[Name:CAURB02]			=		消防栓
[Name:CATIME02]			=		时间机器
[Name:CAURB01]			=		电话亭
[Name:DNOB]				=		腕龙
[Name:BPLN]				=		米格战机
[Name:JEEP]				=		吉普车
[Name:YACOMD]			=		尤里指挥中心
[Name:REDBUS]			=		巴士
[Name:GLOBE]			=		球状戏院
[Name:ALL06MD]			=		军事行动：万圣节
[Name:CAPOWR]			=		科技电厂
[Name:CIVILIAN_PLANE]	=		民航机
[Name:PSYREVEAL]		=		心灵控制感测
[Name:CALUNR01]			=		登月小艇
[Name:HERO1]			=		牛仔
[Name:HERO2]			=		健美先生
[Name:HERO3]			=		英雄
