[Info]
Name=盖特模块
DescShort=盖特系统模块
DescLong=记得自己适配WeaponCount什么的

[Register]
****=FlagPack

[****]
IsGattling=yes
TurretCount=1
WeaponCount=6
#Weapon1=
#EliteWeapon1=
#Weapon2=
#EliteWeapon2=
#Weapon3=
#EliteWeapon3=
#Weapon4=
#EliteWeapon4=
#Weapon5=
#EliteWeapon5=
#Weapon6=
#EliteWeapon6=
#WeaponStages=3
Stage1=
Stage2=
Stage3=
EliteStage1=
EliteStage2=
EliteStage3=
RateUp=1
RateDown=50

