;INI织网者 V1.0
;这是一个生成模块的样板
;生成于 2025年07月08日 星期二 21:33:01

[Info]
Name = AITriggerTypes
DescShort = AITriggerTypes
DescLong = AITriggerTypes
ParamDescShort = 
ParamDescLong = 

[Register]

****=FlagPack

[****]
WeaverAIIniMagic=
