;INI织网者 V1.0
;这是一个生成模块的样板
;生成于 2025年07月08日 星期二 21:33:01

[Info]
Name = 语句包说明1
DescShort = 特别提示
DescLong =语句包和各种语句的字典为AI录入。大语言模型写的脚本可没有那么精准，何况原始资料也不是统一格式的，难免有些地方切分出问题。如有异常和不准确，以RA2DIY论坛2025年版教程内提供的参考资料为准。欢迎前往用户群905426530反馈。语句包名称中写的大类名称说明这个包应该插入什么类型的模块。
ParamDescShort = 
ParamDescLong = 

[Register]

****=FlagPack

[****]
