;INI织网者 V1.0
;这是一个生成模块的样板
;生成于 2025年07月08日 星期二 21:33:01

[Info]
Name = 尤里支援射击黑箱
DescShort = 将入口武器接入ExtraFire
DescLong = 被心控的单位攻击时，尤里也发出攻击
ParamDescShort = 
ParamDescLong = 



[Register]
Rules#****0 = WeaponTypes
Rules#****1 = Warheads
Rules#****2 = Stack
Rules#****3 = Stack
Rules#****4 = Stack
Rules#****5 = AEAnim
Rules#****6 = AEAnim
Rules#****7 = Stack
Rules#****8 = Stack
Rules#****9 = ExtraFire
Rules#****10 = WeaponTypes
Rules#****11 = AEAnim
Rules#****12 = AutoWeapon
Rules#****13 = WeaponTypes
Rules#****14 = Warheads
Rules#****15 = AutoWeapon


Rules#[****0]:[20mm]
ImportDeltaX = -72.978348
ImportDeltaY = -10.751612
TechnoTypes#DefaultLink = Primary
AutoWeapon#DefaultLink = AutoWeapon.Types
ExtraFire#DefaultLink = ExtraFire.Primary
Revenge#DefaultLink = Revenge.Types
ProjectileTypes#DefaultLink = ShrapnelWeapon
InfantryTypes#DefaultLink = Primary
VehicleTypes#DefaultLink = Primary
AircraftTypes#DefaultLink = Primary
BuildingTypes#DefaultLink = Primary
#Warhead = ****1
Damage = 1
Report = none


Rules#[****1]:[TOY]
ImportDeltaX = -55.582523
ImportDeltaY = -10.439112
WeaponTypes#DefaultLink = Warhead
Particles#DefaultLink = Warhead
#AttachEffectTypes = ****4,****2


Rules#[****2]
ImportDeltaX = -38.780037
ImportDeltaY = -15.817554
WeaponTypes#DefaultLink = Feedback.AttachEffects
Warheads#DefaultLink = AttachEffectTypes
ProjectileTypes#DefaultLink = AttachEffectTypes
DamageReaction#DefaultLink = DamageReaction.TriggeredAttachEffects
Host#DefaultLink = Host.AttachEffects
TechnoTypes#DefaultLink = AttachEffectTypes
Broadcast#DefaultLink = Broadcast.Types
Revenge#DefaultLink = Revenge.AttachEffects
GiftBox#DefaultLink = GiftBox.AttachEffects
InfantryTypes#DefaultLink = AttachEffectTypes
VehicleTypes#DefaultLink = AttachEffectTypes
AircraftTypes#DefaultLink = AttachEffectTypes
BuildingTypes#DefaultLink = AttachEffectTypes
#Stack.AttachEffects = ****3
#Stack.Watch = ****2
Stack.Level = 1
Stack.Condition = EQ
Duration = 1
Stack.AttachToSource = yes


Rules#[****3]
ImportDeltaX = -12.880872
ImportDeltaY = -21.180988
WeaponTypes#DefaultLink = Feedback.AttachEffects
Warheads#DefaultLink = AttachEffectTypes
ProjectileTypes#DefaultLink = AttachEffectTypes
DamageReaction#DefaultLink = DamageReaction.TriggeredAttachEffects
Host#DefaultLink = Host.AttachEffects
TechnoTypes#DefaultLink = AttachEffectTypes
Broadcast#DefaultLink = Broadcast.Types
Revenge#DefaultLink = Revenge.AttachEffects
GiftBox#DefaultLink = GiftBox.AttachEffects
InfantryTypes#DefaultLink = AttachEffectTypes
VehicleTypes#DefaultLink = AttachEffectTypes
AircraftTypes#DefaultLink = AttachEffectTypes
BuildingTypes#DefaultLink = AttachEffectTypes
#Stack.Watch = ****3
#Stack.RemoveEffects = ****5,****6,****7
InitialDelay = 5
Duration = 1
Stack.RemoveSkipNext = yes
Stack.Level = 1
Stack.Condition = EQ


Rules#[****4]
ImportDeltaX = -36.103355
ImportDeltaY = -2.001612
WeaponTypes#DefaultLink = Feedback.AttachEffects
Warheads#DefaultLink = AttachEffectTypes
ProjectileTypes#DefaultLink = AttachEffectTypes
DamageReaction#DefaultLink = DamageReaction.TriggeredAttachEffects
Host#DefaultLink = Host.AttachEffects
TechnoTypes#DefaultLink = AttachEffectTypes
Broadcast#DefaultLink = Broadcast.Types
Revenge#DefaultLink = Revenge.AttachEffects
GiftBox#DefaultLink = GiftBox.AttachEffects
InfantryTypes#DefaultLink = AttachEffectTypes
VehicleTypes#DefaultLink = AttachEffectTypes
AircraftTypes#DefaultLink = AttachEffectTypes
BuildingTypes#DefaultLink = AttachEffectTypes
#Stack.AttachEffects = ****7,****5
#Stack.Watch = ****4
InitialDelay = 20
Stack.Level = 1
Stack.Condition = EQ
Duration = 1
Stack.AttachToSource = yes


Rules#[****5]
ImportDeltaX = -10.270022
ImportDeltaY = -1.584945
AEAnim#DefaultLink = Next
AttachEffectTypes#DefaultLink = Next
WeaponTypes#DefaultLink = Feedback.AttachEffects
Warheads#DefaultLink = AttachEffectTypes
Pump#DefaultLink = Next
ProjectileTypes#DefaultLink = AttachEffectTypes
DamageReaction#DefaultLink = DamageReaction.TriggeredAttachEffects
TechnoTypes#DefaultLink = AttachEffectTypes
Stack#DefaultLink = Next
Host#DefaultLink = Host.AttachEffects
Status#DefaultLink = Next
Broadcast#DefaultLink = Broadcast.Types
Revenge#DefaultLink = Revenge.AttachEffects
GiftBox#DefaultLink = GiftBox.AttachEffects
DestroyAnim#DefaultLink = Next
DamageSelf#DefaultLink = Next
Info#DefaultLink = Next
Stand#DefaultLink = Next
AttackBeacon#DefaultLink = Next
BlackHole#DefaultLink = Next
AutoWeapon#DefaultLink = Next
Paintball#DefaultLink = Next
DestroySelf#DefaultLink = Next
Transform#DefaultLink = Next
Immune#DefaultLink = Next
Vampire#DefaultLink = Next
Bounce#DefaultLink = Next
ExtraFire#DefaultLink = Next
FireSuperWeapon#DefaultLink = Next
NoMoneyNoTalk#DefaultLink = Next
DisableWeapon#DefaultLink = Next
OverrideWeapon#DefaultLink = Next
Freeze#DefaultLink = Next
NoSelect#DefaultLink = Next
Teleport#DefaultLink = Next
Scatter#DefaultLink = Next
ECM#DefaultLink = Next
InfantryTypes#DefaultLink = AttachEffectTypes
VehicleTypes#DefaultLink = AttachEffectTypes
AircraftTypes#DefaultLink = AttachEffectTypes
BuildingTypes#DefaultLink = AttachEffectTypes
#Next = ****6
#Animation = INVISO
Duration = 5


Rules#[****6]
ImportDeltaX = 13.641302
ImportDeltaY = -21.532881
AEAnim#DefaultLink = Next
AttachEffectTypes#DefaultLink = Next
WeaponTypes#DefaultLink = Feedback.AttachEffects
Warheads#DefaultLink = AttachEffectTypes
Pump#DefaultLink = Next
ProjectileTypes#DefaultLink = AttachEffectTypes
DamageReaction#DefaultLink = DamageReaction.TriggeredAttachEffects
TechnoTypes#DefaultLink = AttachEffectTypes
Stack#DefaultLink = Next
Host#DefaultLink = Host.AttachEffects
Status#DefaultLink = Next
Broadcast#DefaultLink = Broadcast.Types
Revenge#DefaultLink = Revenge.AttachEffects
GiftBox#DefaultLink = GiftBox.AttachEffects
DestroyAnim#DefaultLink = Next
DamageSelf#DefaultLink = Next
Info#DefaultLink = Next
Stand#DefaultLink = Next
AttackBeacon#DefaultLink = Next
BlackHole#DefaultLink = Next
AutoWeapon#DefaultLink = Next
Paintball#DefaultLink = Next
DestroySelf#DefaultLink = Next
Transform#DefaultLink = Next
Immune#DefaultLink = Next
Vampire#DefaultLink = Next
Bounce#DefaultLink = Next
ExtraFire#DefaultLink = Next
FireSuperWeapon#DefaultLink = Next
NoMoneyNoTalk#DefaultLink = Next
DisableWeapon#DefaultLink = Next
OverrideWeapon#DefaultLink = Next
Freeze#DefaultLink = Next
NoSelect#DefaultLink = Next
Teleport#DefaultLink = Next
Scatter#DefaultLink = Next
ECM#DefaultLink = Next
InfantryTypes#DefaultLink = AttachEffectTypes
VehicleTypes#DefaultLink = AttachEffectTypes
AircraftTypes#DefaultLink = AttachEffectTypes
BuildingTypes#DefaultLink = AttachEffectTypes
#Next = ****5
#Animation = INVISO
Duration = 40


Rules#[****7]
ImportDeltaX = 13.953800
ImportDeltaY = -5.673506
WeaponTypes#DefaultLink = Feedback.AttachEffects
Warheads#DefaultLink = AttachEffectTypes
ProjectileTypes#DefaultLink = AttachEffectTypes
DamageReaction#DefaultLink = DamageReaction.TriggeredAttachEffects
Host#DefaultLink = Host.AttachEffects
TechnoTypes#DefaultLink = AttachEffectTypes
Broadcast#DefaultLink = Broadcast.Types
Revenge#DefaultLink = Revenge.AttachEffects
GiftBox#DefaultLink = GiftBox.AttachEffects
InfantryTypes#DefaultLink = AttachEffectTypes
VehicleTypes#DefaultLink = AttachEffectTypes
AircraftTypes#DefaultLink = AttachEffectTypes
BuildingTypes#DefaultLink = AttachEffectTypes
#Stack.AttachEffects = ****9,****8
#Stack.Watch = ****5
HoldDuration = yes
Duration = 100
Stack.Level = 1
Stack.Condition = EQ
Stack.AttachToSource = yes


Rules#[****8]
ImportDeltaX = 33.159901
ImportDeltaY = -4.606902
WeaponTypes#DefaultLink = Feedback.AttachEffects
Warheads#DefaultLink = AttachEffectTypes
ProjectileTypes#DefaultLink = AttachEffectTypes
DamageReaction#DefaultLink = DamageReaction.TriggeredAttachEffects
Host#DefaultLink = Host.AttachEffects
TechnoTypes#DefaultLink = AttachEffectTypes
Broadcast#DefaultLink = Broadcast.Types
Revenge#DefaultLink = Revenge.AttachEffects
GiftBox#DefaultLink = GiftBox.AttachEffects
InfantryTypes#DefaultLink = AttachEffectTypes
VehicleTypes#DefaultLink = AttachEffectTypes
AircraftTypes#DefaultLink = AttachEffectTypes
BuildingTypes#DefaultLink = AttachEffectTypes
#Stack.AttachEffects = ****12
#Stack.Watch = ****11
ResetDurationOnReapply = yes
Duration = 50
Stack.Level = 1
Stack.Condition = EQ


Rules#[****9]
ImportDeltaX = -29.308880
ImportDeltaY = 15.417655
WeaponTypes#DefaultLink = Feedback.AttachEffects
Warheads#DefaultLink = AttachEffectTypes
ProjectileTypes#DefaultLink = AttachEffectTypes
DamageReaction#DefaultLink = DamageReaction.TriggeredAttachEffects
Host#DefaultLink = Host.AttachEffects
TechnoTypes#DefaultLink = AttachEffectTypes
Broadcast#DefaultLink = Broadcast.Types
Revenge#DefaultLink = Revenge.AttachEffects
GiftBox#DefaultLink = GiftBox.AttachEffects
InfantryTypes#DefaultLink = AttachEffectTypes
VehicleTypes#DefaultLink = AttachEffectTypes
AircraftTypes#DefaultLink = AttachEffectTypes
BuildingTypes#DefaultLink = AttachEffectTypes
#ExtraFire.Primary = ****10
#ExtraFire.Secondary = ****10
#ExtraFire.ElitePrimary = ****10
#ExtraFire.EliteSecondary = ****10
#ExtraFire.Weapon1 = ****10
#ExtraFire.EliteWeapon1 = ****10
Duration = 50
ResetDurationOnReapply = yes


Rules#[****10]:[20mm]
ImportDeltaX = -0.469591
ImportDeltaY = 15.060511
TechnoTypes#DefaultLink = Primary
AutoWeapon#DefaultLink = AutoWeapon.Types
ExtraFire#DefaultLink = ExtraFire.Primary
Revenge#DefaultLink = Revenge.Types
ProjectileTypes#DefaultLink = ShrapnelWeapon
InfantryTypes#DefaultLink = Primary
VehicleTypes#DefaultLink = Primary
AircraftTypes#DefaultLink = Primary
BuildingTypes#DefaultLink = Primary
#Warhead = TOY
#Feedback.AttachEffects = ****11
Damage = 1
Report = none


Rules#[****11]
ImportDeltaX = 25.244699
ImportDeltaY = 16.667654
AEAnim#DefaultLink = Next
AttachEffectTypes#DefaultLink = Next
WeaponTypes#DefaultLink = Feedback.AttachEffects
Warheads#DefaultLink = AttachEffectTypes
Pump#DefaultLink = Next
ProjectileTypes#DefaultLink = AttachEffectTypes
DamageReaction#DefaultLink = DamageReaction.TriggeredAttachEffects
TechnoTypes#DefaultLink = AttachEffectTypes
Stack#DefaultLink = Next
Host#DefaultLink = Host.AttachEffects
Status#DefaultLink = Next
Broadcast#DefaultLink = Broadcast.Types
Revenge#DefaultLink = Revenge.AttachEffects
GiftBox#DefaultLink = GiftBox.AttachEffects
DestroyAnim#DefaultLink = Next
DamageSelf#DefaultLink = Next
Info#DefaultLink = Next
Stand#DefaultLink = Next
AttackBeacon#DefaultLink = Next
BlackHole#DefaultLink = Next
AutoWeapon#DefaultLink = Next
Paintball#DefaultLink = Next
DestroySelf#DefaultLink = Next
Transform#DefaultLink = Next
Immune#DefaultLink = Next
Vampire#DefaultLink = Next
Bounce#DefaultLink = Next
ExtraFire#DefaultLink = Next
FireSuperWeapon#DefaultLink = Next
NoMoneyNoTalk#DefaultLink = Next
DisableWeapon#DefaultLink = Next
OverrideWeapon#DefaultLink = Next
Freeze#DefaultLink = Next
NoSelect#DefaultLink = Next
Teleport#DefaultLink = Next
Scatter#DefaultLink = Next
ECM#DefaultLink = Next
InfantryTypes#DefaultLink = AttachEffectTypes
VehicleTypes#DefaultLink = AttachEffectTypes
AircraftTypes#DefaultLink = AttachEffectTypes
BuildingTypes#DefaultLink = AttachEffectTypes
#Animation = INVISO
Duration = 10


Rules#[****12]
ImportDeltaX = 58.159897
ImportDeltaY = -5.678332
WeaponTypes#DefaultLink = Feedback.AttachEffects
Warheads#DefaultLink = AttachEffectTypes
ProjectileTypes#DefaultLink = AttachEffectTypes
DamageReaction#DefaultLink = DamageReaction.TriggeredAttachEffects
Host#DefaultLink = Host.AttachEffects
TechnoTypes#DefaultLink = AttachEffectTypes
Broadcast#DefaultLink = Broadcast.Types
Revenge#DefaultLink = Revenge.AttachEffects
GiftBox#DefaultLink = GiftBox.AttachEffects
InfantryTypes#DefaultLink = AttachEffectTypes
VehicleTypes#DefaultLink = AttachEffectTypes
AircraftTypes#DefaultLink = AttachEffectTypes
BuildingTypes#DefaultLink = AttachEffectTypes
#AutoWeapon.Types = ****13
AutoWeapon.FireToTarget = yes
AutoWeapon.FireOnce = yes
AutoWeapon.ReceiverOwnBullet = no


Rules#[****13]:[20mm]
ImportDeltaX = 52.713470
ImportDeltaY = 4.321669
TechnoTypes#DefaultLink = Primary
AutoWeapon#DefaultLink = AutoWeapon.Types
ExtraFire#DefaultLink = ExtraFire.Primary
Revenge#DefaultLink = Revenge.Types
ProjectileTypes#DefaultLink = ShrapnelWeapon
InfantryTypes#DefaultLink = Primary
VehicleTypes#DefaultLink = Primary
AircraftTypes#DefaultLink = Primary
BuildingTypes#DefaultLink = Primary
#Warhead = ****14
Damage = 1
Report = none


Rules#[****14]:[TOY]
ImportDeltaX = 53.784893
ImportDeltaY = 16.107382
WeaponTypes#DefaultLink = Warhead
Particles#DefaultLink = Warhead
#AttachEffectTypes = ****15
AffectsAllies = no


Rules#[****15]
ImportDeltaX = 54.499180
ImportDeltaY = 26.464525
WeaponTypes#DefaultLink = Feedback.AttachEffects
Warheads#DefaultLink = AttachEffectTypes
ProjectileTypes#DefaultLink = AttachEffectTypes
DamageReaction#DefaultLink = DamageReaction.TriggeredAttachEffects
Host#DefaultLink = Host.AttachEffects
TechnoTypes#DefaultLink = AttachEffectTypes
Broadcast#DefaultLink = Broadcast.Types
Revenge#DefaultLink = Revenge.AttachEffects
GiftBox#DefaultLink = GiftBox.AttachEffects
InfantryTypes#DefaultLink = AttachEffectTypes
VehicleTypes#DefaultLink = AttachEffectTypes
AircraftTypes#DefaultLink = AttachEffectTypes
BuildingTypes#DefaultLink = AttachEffectTypes
#AutoWeapon.Types = LunarLaser
AutoWeapon.IsAttackerMark = yes
AutoWeapon.ReceiverAttack = no
AutoWeapon.FireOnce = yes
AutoWeapon.FireFLH = 15,0,140


