;INI浏览器 0.2
;这是一个自建模块的样板
;如果需要创建来自剪贴板的模块，可以直接用剪贴板的内容覆盖Data一行
;之后填上自己的Desc即可
[Info]
Name=CircleVectorLinear
DescShort=圆弧-角速度模式
DescLong=以角速度设置的圆弧.OriginFLH圆高为相对抛射体高度，CircleOrigin为绝对高度。CircleRadius=0就是抛射体和圆心的XY距离

[Register]
; INI类型#注册名=类型，INI类型默认Rules
****=Vector

[****]
Duration=114514
#Vector.Origin=Target
Vector.OriginNoUpdate=no
AttachOnceInTechnoType=yes
Vector.CircleAnglePerStep=30
Vector.OriginFLH=0,0,0
Vector.CircleOrigin=0,0,0
Vector.CircleRadius=600
Vector.NormalVector=0,0,0
Vector.AllowCircleTilt=no
Vector.Lissajous=0
Vector.CircleDynamic=no
