;INI浏览器 0.2
;这是一个自建模块的样板
;如果需要创建来自剪贴板的模块，可以直接用剪贴板的内容覆盖Data一行
;之后填上自己的Desc即可
[Info]
Name=ReachTargetVector
DescShort=ReachTarget模式
DescLong=Duration结束时必定抵达目标

[Register]
; INI类型#注册名=类型，INI类型默认Rules
****=Vector

[****]
Duration=20
Vector.TargetFLH=0,0,0
  
#Vector.ReachTarget=yes
Vector.Force=yes
#Vector.Origin=Target
#Vector.OriginNoUpdate=no
AttachOnceInTechnoType=yes
#Vector.ReachTargetEarlyEnd=0
#Vector.DisabledFrames=0

