;INI浏览器 0.2
;这是一个自建模块的样板
;如果需要创建来自剪贴板的模块，可以直接用剪贴板的内容覆盖Data一行
;之后填上自己的Desc即可
[Info]
Name=10-Info                       ;每个模块独一无二的注册名
DescShort=Info
DescLong=显示Info
[Register]
; INI类型#注册名=类型，INI类型默认Rules
****=AEAnim

[****]
Info.Duration.Mode=TEXT
Info.Duration.Watch=
#HoldDuration=yeaaaaaaah
#Duration=3

ResetDurationOnReapply=yeaaaaaaah
AttachOnceInTechnoType=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck
