;INI浏览器 0.2
;这是一个自建模块的样板
;如果需要创建来自剪贴板的模块，可以直接用剪贴板的内容覆盖Data一行
;之后填上自己的Desc即可
[Info]
Name=11-四蛋都怕我                       ;每个模块独一无二的注册名
DescShort=Stand
DescLong=替身 —— AE生效期间，为附着对象添加一个独立单位做替身，替身会始终跟随使者行动
[Register]
; INI类型#注册名=类型，INI类型默认Rules
****=Stand

[****]

#Stand.Type=
Stand.Offset=0,0,0 ;替身的位置，单位的FLH，+F在建筑的右下方
Stand.StackOffset=0,0,0 ;如果出现多个相同的AE堆叠时，当前替身相比于上一个替身的位置偏移
Stand.StackGroup=-1 ;分组堆叠，同一个组的替身堆叠在一起，后一个替身以同组的上一个替身位置偏移
Stand.StackGroupOffset=0,0,0 ;分组堆叠，当前组相比于上一组的位置偏移
Stand.Direction=0 ;替身的初始朝向，[0-15]，16分圆，0是替身前方，单位为右上，建筑为右下，16方向：N=0、NE=2、E=4、SE=6、S=8、SW=10、W=12、NW=14
#Stand.LockDirection=fuuuuuuuuck ;强制固定替身朝向始终保持与使者的方位，无论替身是否正在攻击目标
#Stand.FreeDirection=fuuuuuuuuck ;完全不控制替身的朝向，由替身自由行动，默认情况下替身会在失去目标之后回归到初始朝向
#Stand.IsOnTurret=fuuuuuuuuck ;替身绑定在炮管上
Stand.IsOnWorld=fuuuuuuuuck ;替身绑定位置以世界坐标做参考，固定朝向北方，不跟随转动
Stand.ZOffset=1 ;替身在渲染时YSort偏移值，正值显示在JOJO上层，负值在下层，火车类型无效
Stand.SameTilter=yeaaaaaaah ;替身和使者同为Drive Locomotor时，强制同步替身的倾斜角度。关闭时Drive Loco的替身会自行根据所处的格子倾斜自身。
#Stand.SameMoving=fuuuuuuuuck ;替身在使者移动时，也播放移动动画，并且朝向和使者一致，不影响火车
Stand.StickOnFloor=yeaaaaaaah ;替身在使者移动时，如果需要播放移动动画，将保持贴在地上，替身为Jumpjet时无效，不影响火车
Stand.SameHouse=yeaaaaaaah ;替身跟随附属对象的所属变化，本体属性变化如心控，替身所属也跟随变化
Stand.SameTarget=yeaaaaaaah ;强制替身与使者攻击同一个目标
#Stand.SameLoseTarget=fuuuuuuuuck ;使者失去目标同时替身也失去
Stand.SameAmmo=fuuuuuuuuck ;强制替身弹药数量与使者相同
Stand.UseMasterAmmo=fuuuuuuuuck ;替身在开火时消耗使者的弹药，SameAmmo启用时自动开启
Stand.Targeting=BOTH ;替身在什么位置可以攻击，BOTH\LAND\AIR，LAND只能在地上开火，AIR只能在空中开火
#Stand.ForceAttackMaster=fuuuuuuuuck ;替身强制选定使者为目标
#Stand.AttackSource=fuuuuuuuuck ;如果替身可以攻击AE来源，那么在生成时会选定AE来源为目标
Stand.MobileFire=yeaaaaaaah ;使者在移动时替身仍可攻击
Stand.Powered=fuuuuuuuuck ;替身需要电力支持才能攻击
#Stand.Immune=yeaaaaaaah ;替身是否可以收到伤害
Stand.DamageFromMaster=0.0 ;替身是否分摊使者收到的伤害，如果替身无法受伤，则不会分摊，如果弹头无法对替身造成伤害，同样分摊
Stand.DamageToMaster=0.0 ;使者是否分摊替身收到的伤害，如果使者无法受伤，则不会分摊，如果弹头无法对使者造成伤害，同样分摊
#Stand.Explodes=fuuuuuuuuck ;AE结束时，替身爆炸，被打死的不算
#Stand.ExplodesWithMaster=fuuuuuuuuck ;替身在JOJO死亡时爆炸，覆盖上一条设置，被打死的不算
Stand.ExplodesWithRocket=yeaaaaaaah ;替身绑定在火箭上时，火箭撞击爆炸时爆炸，被打死的不算
Stand.RemoveAtSinking=fuuuuuuuuck ;使者沉船时移除替身
Stand.PromoteFromMaster=fuuuuuuuuck ;强制替身等级与使者相同
Stand.PromoteFromSpawnOwner=fuuuuuuuuck ;替身绑定在子机上时，强制替身等级与子机发射者相同
Stand.ExperienceToMaster=0.0 ;替身可以训练时，分多少经验给使者，替身不能训练时，击杀100%经验转给使者
Stand.ExperienceToSpawnOwner=fuuuuuuuuck ;替身绑定在子机上时，经验分给子机发射者而不是子机
Stand.SelectToMaster=fuuuuuuuuck ;当替身被选中时，转移选中使者
#Stand.VirtualUnit=yeaaaaaaah ; 虚拟单位，不存在于地图上的单位，不可以被选中
Stand.IsVirtualTurret=yeaaaaaaah ;替身是否作为使者的炮塔存在，同步使者的火力、护甲和ROF加成；设为no时不同步火力、护甲和ROF，但无法解除超时空、隐形的同步
Stand.IsTrain=fuuuuuuuuck ;火车类型的替身，特殊表现，跟随使者行动轨迹
Stand.IsCabinHead=fuuuuuuuuck ;火车类型的替身，在生成时是否插入车厢组前端
Stand.CabinGroup=-1 ;火车类型的替身，车厢的分组


#HoldDuration=yeaaaaaaah
#Duration=3

ResetDurationOnReapply=yeaaaaaaah
AttachOnceInTechnoType=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck
