;INI浏览器 0.2
;这是一个自建模块的样板
;如果需要创建来自剪贴板的模块，可以直接用剪贴板的内容覆盖Data一行
;之后填上自己的Desc即可
[Info]
Name=2-AutoWeaponFireToTarget
DescShort=AutoWeapon.FireToTarget
DescLong=自动武器-对目标/坐标开火。AE生效期间，自动的使用武器攻击一个指定的坐标或单位自身的目标
[Register]
; INI类型#注册名=类型，INI类型默认Rules
****=AutoWeapon

[****]
AttachOnceInTechnoType=yeaaaaaaah
Duration=3
HoldDuration=fuuuuuuuuck
#AutoWeapon.FireOnce=yeaaaaaaah
#AutoWeapon.Types=
#AutoWeapon.FireToTarget=yeaaaaaaah
#AutoWeapon.TargetFLH=0,0,0


ResetDurationOnReapply=yeaaaaaaah
AttachOnceInTechnoType=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck
