
;INI浏览器 0.2
;这是一个自建模块的样板
;如果需要创建来自剪贴板的模块，可以直接用剪贴板的内容覆盖Data一行
;之后填上自己的Desc即可
[Info]
Name=3-Stack
DescShort=Stack
DescLong=层数检测 —— AE生效期间，监视某个AE的叠加层数达到指定层数，为持有者添加新的AE，被超时空冻结时仍然有效
[Register]
; INI类型#注册名=类型，INI类型默认Rules
****=Stack

[****]
#Stack.Watch=****
Stack.Level=1
Stack.Condition=EQ
#Stack.AttachEffects=
Duration=2
Stack.RemoveAll=fuuuuuuuuck
Stack.TriggeredTimes=1
Stack.ActionMode=AND
#Stack.AttachToSource=fuuuuuuuuck
ResetDurationOnReapply=yeaaaaaaah
AttachOnceInTechnoType=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck
