;INI浏览器 0.2
;这是一个自建模块的样板
;如果需要创建来自剪贴板的模块，可以直接用剪贴板的内容覆盖Data一行
;之后填上自己的Desc即可
[Info]
Name=4-Broadcast Simple                       ;每个模块独一无二的注册名
DescShort=Broadcast
DescLong=AE生效期间，间歇性向周围的单位附加AE，通过广播传播的AE的来源是广播AE本身的来源，可通过设置AE本身的ReceiverOwn来调整广播自身的来源，默认通过弹头附加的广播，来源是释放该弹头的攻击者，

[Register]
; INI类型#注册名=类型，INI类型默认Rules
****=Broadcast

[****]
AttachOnceInTechnoType=yeaaaaaaah
Duration=2
#Broadcast.Types=
Broadcast.Rate=1
Broadcast.RangeMin=0
Broadcast.RangeMax=-1
#Broadcast.TriggeredTimes=1
Broadcast.AffectsOwner=yeaaaaaaah
Broadcast.AffectsAllies=fuuuuuuuuck
Broadcast.AffectsEnemies=fuuuuuuuuck
Broadcast.AffectsCivilian=fuuuuuuuuck
ReceiverOwn=yeaaaaaaah


ResetDurationOnReapply=yeaaaaaaah
AttachOnceInTechnoType=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck
