;INI浏览器 0.2
;这是一个自建模块的样板
;如果需要创建来自剪贴板的模块，可以直接用剪贴板的内容覆盖Data一行
;之后填上自己的Desc即可
[Info]
Name=5-Host                      ;每个模块独一无二的注册名
DescShort=Host             ;短描述
DescLong=刷怪笼 —— AE生效期间，间断性的在身边刷出单位

[Register]
; INI类型#注册名=类型，INI类型默认Rules
****=Host

[****]

Duration=3
InitialDelay=1
#Host.Types=
#Host.AttachEffects=
Host.TriggeredTimes=1


ResetDurationOnReapply=yeaaaaaaah
AttachOnceInTechnoType=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck
