;INI浏览器 0.2
;这是一个自建模块的样板
;如果需要创建来自剪贴板的模块，可以直接用剪贴板的内容覆盖Data一行
;之后填上自己的Desc即可
[Info]
Name=6-Counter
DescShort=Counter
DescLong=计数器 —— AE生效期间，获得一个计数器，可以通过其他AE对计数器进行操作，计数器的数值操作只会在相关AE被赋予时进行
[Register]
; INI类型#注册名=类型，INI类型默认Rules
****=Counter

[****]

Counter.Mark=****
#Counter.Num=0 ;赋予时的计数值，可以用特殊值HP、MAXHP读取当前单位的血量作为计数，对于抛射体，HP即抛射体的威力
Counter.NumFromSource=fuuuuuuuuck ;当Num使用特殊值时，优先读取来源
#Counter.Min=0 ;计数器的最小值
#Counter.Max=-1 ;计数器的最大值，-1表示不限制
Counter.Action=ADD 
Counter.AttachIfNotFound=yeaaaaaaah 
Counter.RemoveWhenNum=0,-1 
Counter.Reaction=fuuuuuuuuckRMAL 
#HoldDuration=yeaaaaaaah
#Duration=3
Info.Counter.Watch=****
Info.Counter.Mode=TEXT


ResetDurationOnReapply=yeaaaaaaah
AttachOnceInTechnoType=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck
