;INI浏览器 0.2
;这是一个自建模块的样板
;如果需要创建来自剪贴板的模块，可以直接用剪贴板的内容覆盖Data一行
;之后填上自己的Desc即可
[Info]
Name=7-CounterTrigger
DescShort=CounterTrigger
DescLong=计数触发器 —— 与计数器分离的单独触发器，在执行时检查监视的计数器值，满足条件时触发效果
[Register]
; INI类型#注册名=类型，INI类型默认Rules
****=CounterTrigger

[****]
Duration=3

CountTrigger.Watch=
#CountTrigger.Range=
CountTrigger.TriggeredTimes=1 
CountTrigger.RemoveCounter=fuuuuuuuuck ;移除计数器，若存在多个触发器，后续的触发将停止执行
; 赋予效果
CountTrigger.AttachEffects=
CountTrigger.AttachTo=ME ;触发后向谁附加AE，ME\SOURCE\COUNTERSOURCE
CountTrigger.AttachFrom=SOURCE ;附加效果的来源设置，ME\SOURCE\COUNTERSOURCE
CountTrigger.RemoveEffects=
CountTrigger.RemoveEffectsLevel=
CountTrigger.RemoveEffectsWithMarks=
CountTrigger.RemoveEffectsSkipNext=fuuuuuuuuck
CountTrigger.RemoveWho=ME ;触发后移除谁身上的AE，ME\SOURCE\COUNTERSOURCE


ResetDurationOnReapply=yeaaaaaaah
AttachOnceInTechnoType=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck
