;INI浏览器 0.2
;这是一个自建模块的样板
;如果需要创建来自剪贴板的模块，可以直接用剪贴板的内容覆盖Data一行
;之后填上自己的Desc即可
[Info]
Name=8-CounterModifier
DescShort=CounterModifier
DescLong=计数器修改器，实际上还是触发器
[Register]
; INI类型#注册名=类型，INI类型默认Rules
****=CounterTrigger

[****]
Duration=3

CountTrigger.Watch=
CountTrigger.Range=514,114
CountTrigger.TriggeredTimes=1 
#CountTrigger.Num=1
CountTrigger.NumFrom=ME ;当Num使用特殊值时，ME\SOURCE\COUNTERSOURCE，自身、自身来源、计数器来源
CountTrigger.Action=ADD ;计数器的操作，ADD=增加，INIT=设置，SUB=减少，MUL=倍数
CountTrigger.ResetNum=fuuuuuuuuck ;重置计数器为计数器初始值Num
CountTrigger.RemoveCounter=fuuuuuuuuck ;移除计数器，若存在多个触发器，后续的触发将停止执行


ResetDurationOnReapply=yeaaaaaaah
AttachOnceInTechnoType=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck
