;INI浏览器 0.2
;这是一个自建模块的样板
;如果需要创建来自剪贴板的模块，可以直接用剪贴板的内容覆盖Data一行
;之后填上自己的Desc即可
[Info]
Name=FireSuperWeapon
DescShort=FireSuperWeapon
DescLong=发射超级武器 —— AE生效期间，附着的单位发射武器时，一并发射指定的超级武器，无法对抛射体生效
[Register]
; INI类型#注册名=类型，INI类型默认Rules
****=FireSuperWeapon

[****]
Duration=3
HoldDuration=yeaaaaaaah
AttachOnceInTechnoType=yeaaaaaaah
FireSuperWeapon.Types=
FireSuperWeapon.Chances=1.0
FireSuperWeapon.LaunchCount=1
FireSuperWeapon.RealLaunch=fuuuuuuuuck
FireSuperWeapon.Weapon=-1
FireSuperWeapon.ToTarget=yeaaaaaaah
FireSuperWeapon.Reload=0
FireSuperWeapon.TriggeredTimes=1 
FireSuperWeapon.DeactiveWhenCivilian=fuuuuuuuuck

ResetDurationOnReapply=yeaaaaaaah
AttachOnceInTechnoType=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck
