;INI浏览器 0.2
;这是一个自建模块的样板
;如果需要创建来自剪贴板的模块，可以直接用剪贴板的内容覆盖Data一行
;之后填上自己的Desc即可
[Info]
Name=免疫
DescShort=Immune
DescLong=免疫——AE生效期间，单位会免疫特殊攻击，不会解除已经遭受的特殊攻击

[Register]
; INI类型#注册名=类型，INI类型默认Rules
****=Immune

[****]
Immune.Psionics=fuuuuuuuuck ;免疫心灵控制
Immune.PsionicWeapons=fuuuuuuuuck ;免疫心灵震爆
Immune.Radiation=fuuuuuuuuck ;免疫辐射
Immune.Poison=fuuuuuuuuck ;免疫病毒
Immune.EMP=fuuuuuuuuck ;免疫EMP
Immune.Parasite=fuuuuuuuuck ;免疫寄生
Immune.Temporal=fuuuuuuuuck ;免疫超时空传送
Immune.IsLocomotor=fuuuuuuuuck ;免疫磁电
Immune.AntiWarheads=
Immune.AcceptWarheads=

AttachOnceInTechnoType=yeaaaaaaah
#HoldDuration=yeaaaaaaah
Duration=100
ResetDurationOnReapply=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck

