;INI浏览器 0.2
;这是一个自建模块的样板
;如果需要创建来自剪贴板的模块，可以直接用剪贴板的内容覆盖Data一行
;之后填上自己的Desc即可
[Info]
Name=吸血                      ;每个模块独一无二的注册名
DescShort=Vampire           ;短描述
DescLong=吸血——AE生效期间，附着对象对其他单位造成的伤害，按比例返回

[Register]
; INI类型#注册名=类型，INI类型默认Rules
****=Vampire

[****]
Vampire.Chance=100% ;触发吸血的概率
Vampire.Percent=0% ;吸血的比例
Vampire.TriggeredTimes=-1 ;可触发的次数，次数用完立刻强制结束效果
; 吸血目标对象影响过滤器专属设置
Vampire.AffectTypes= ;类型过滤，可影响的单位，如果设置，则向列表中的单位复仇
Vampire.NotAffectTypes= ;类型过滤，不可影响的单位，如果设置，则不向列表中的单位复仇，优先级更高
; 吸血目标对象影响单位设置
Vampire.AffectBuilding=yeaaaaaaah ;类型过滤，影响建筑
Vampire.AffectInfantry=yeaaaaaaah ;类型过滤，影响步兵
Vampire.AffectUnit=yeaaaaaaah ;类型过滤，影响载具
Vampire.AffectAircraft=yeaaaaaaah ;类型过滤，影响飞机
; 影响特定目标对象
Vampire.AffectInAir=yeaaaaaaah ;影响在空中的单位
Vampire.NotAffectMarks= ;不影响带有这些标记的对象
Vampire.OnlyAffectMarks= ;只影响带有这些标记的对象
; 吸血目标对象敌我识别专属设置
Vampire.AffectsOwner=yeaaaaaaah ;是否影响同阵营的
Vampire.AffectsAllies=yeaaaaaaah ;是否影响友军
Vampire.AffectsEnemies=yeaaaaaaah ;是否影响敌人
Vampire.AffectsCivilian=yeaaaaaaah ;是否影响中立目标
Vampire.DeactiveWhenCivilian=fuuuuuuuuck ;启用时，当所属是平民时，或者被狙掉了驾驶员，不会激活效果


AttachOnceInTechnoType=yeaaaaaaah
#HoldDuration=yeaaaaaaah
Duration=100
ResetDurationOnReapply=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck

