;INI浏览器 0.2
;这是一个自建模块的样板
;如果需要创建来自剪贴板的模块，可以直接用剪贴板的内容覆盖Data一行
;之后填上自己的Desc即可
[Info]
Name=嘲讽信标                     ;每个模块独一无二的注册名
DescShort=AttackBeacon           ;短描述
DescLong=嘲讽信标——吸引特定单位将自身作为目标

[Register]
; INI类型#注册名=类型，INI类型默认Rules
****=AttackBeacon

[****]
AttackBeacon.Enable=yeaaaaaaah ;开启炒粉光环
AttackBeacon.Types=
#AttackBeacon.Nums=-1
AttackBeacon.Rate=30 ;多少帧炒粉一次
AttackBeacon.RangeMin=0 ;炒粉的最小范围，单位：格
AttackBeacon.RangeMax=-1 ;炒粉的最大范围，单位：格
#AttackBeacon.Force=yeaaaaaaah ;不论目标单位在做什么，包括Sleep\Stop，都强制转换目标为自己
AttackBeacon.Count=-1 ;不管是谁，每次炒粉的总数量上限，-1是无限制
AttackBeacon.TriggeredTimes=-1 ;可触发的次数，次数用完立刻强制结束效果

AttackBeacon.AffectsOwner=yeaaaaaaah ;是否影响同阵营的
AttackBeacon.AffectsAllies=yeaaaaaaah ;是否影响友军
AttackBeacon.AffectsEnemies=yeaaaaaaah ;是否影响敌人
AttackBeacon.AffectsCivilian=yeaaaaaaah ;是否影响中立目标

AttachOnceInTechnoType=yeaaaaaaah
#HoldDuration=yeaaaaaaah
Duration=100
ResetDurationOnReapply=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck

