;INI浏览器 0.2
;这是一个自建模块的样板
;如果需要创建来自剪贴板的模块，可以直接用剪贴板的内容覆盖Data一行
;之后填上自己的Desc即可
[Info]
Name=Revenge                      ;每个模块独一无二的注册名
DescShort=Revenge           ;短描述
DescLong=复仇 —— AE生效期间，对打死/伤害单位的攻击者进行复仇，发射武器或直接赋予AE

[Register]
; INI类型#注册名=类型，INI类型默认Rules
****=Revenge

[****]
Revenge.Types=
#HoldDuration=yeaaaaaaah
Revenge.AttachEffects=
#Revenge.ToSource=fuuuuuuuuck
#Revenge.FromSource=fuuuuuuuuck
#Revenge.Realtime=yeaaaaaaah
#AttachOnceInTechnoType=yeaaaaaaah
Duration=100

ResetDurationOnReapply=yeaaaaaaah
AttachOnceInTechnoType=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck

