;INI浏览器 0.2
;这是一个自建模块的样板
;如果需要创建来自剪贴板的模块，可以直接用剪贴板的内容覆盖Data一行
;之后填上自己的Desc即可
[Info]
Name=额外武器
DescShort=ExtraFire
DescLong=额外武器，在主武器/副武器发射的同时发射额外的多个武器，额外武器受单位的精英技能和宝箱加成影响，精英武器不会复用普通武器

[Register]
; INI类型#注册名=类型，INI类型默认Rules
****=ExtraFire

[****]
ExtraFire.Primary=
ExtraFire.ElitePrimary=
ExtraFire.Secondary=
ExtraFire.EliteSecondary=
ExtraFire.Weapon1=
ExtraFire.EliteWeapon1=
; 额外武器的FLH设置，如果AE有设置，则优先使用AE的设置而不使用附着单位的Art的设置
ExtraFire.PrimaryFLH=0,0,0
ExtraFire.ElitePrimaryFLH=0,0,0
ExtraFire.SecondaryFLH=0,0,0
ExtraFire.EliteSecondaryFLH=0,0,0
; 武器FLH不跟随炮塔，以自身朝向计算
ExtraFire.PrimaryOnBody=fuuuuuuuuck
ExtraFire.ElitePrimaryOnBody=fuuuuuuuuck
ExtraFire.SecondaryOnBody=fuuuuuuuuck
ExtraFire.EliteSecondaryOnBody=fuuuuuuuuck
; 武器FLH不以自己计算，以目标位置计算
ExtraFire.PrimaryOnTarget=fuuuuuuuuck
ExtraFire.ElitePrimaryOnTarget=fuuuuuuuuck
ExtraFire.SecondaryOnTarget=fuuuuuuuuck
ExtraFire.EliteSecondaryOnTarget=fuuuuuuuuck
; 盖特和多功能，X=1-127
ExtraFire.Weapon1FLH=0,0,0 ;适用于WeaponX的附加武器设置，X=1\2\3\4，不会覆盖Primary和Secondary
ExtraFire.EliteWeapon1FLH=0,0,0 ;适用于WeaponX的附加武器设置，X=1\2\3\4，不会覆盖Primary和Secondary
ExtraFire.Weapon1OnBody=fuuuuuuuuck
ExtraFire.EliteWeapon1OnBody=fuuuuuuuuck
ExtraFire.Weapon1OnTarget=fuuuuuuuuck
ExtraFire.EliteWeapon1OnTarget=fuuuuuuuuck

AttachOnceInTechnoType=yeaaaaaaah
#HoldDuration=yeaaaaaaah
Duration=100
ResetDurationOnReapply=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck

