;INI织网者 V1.0.8
;这是一个生成模块的样板
;生成于 2026年03月19日 星期四 18:00:23

[Info]
Name = 注释块
DescShort = 注释块
DescLong = 注释块
ParamDescShort = 
ParamDescLong = 
Data = IniBrowserClipDataFormat_1.0.6,694913756,AAEAAAUAAABSdWxlcwAAAAUAAAAqKioqMAAAAJIkCURJkpRD2Xd9tmIVXrcAAAAAAAAAAAAAAAAAAAAAAAAA,EndOfClipData


[Register]


