;INI织网者 V1.0.8
;这是一个生成模块的样板
;生成于 2026年03月14日 星期六 01:37:47

[Info]
Name = 集线器
DescShort = 集线器
DescLong = 集线器



[Register]
Rules#**** = StringList


Rules#[****]
SkipExport#Var=true
SkipTitle#Var=true
WidthRatio#Var=0.5
#Collector.=


