;INI织网者 V1.0.8
;这是一个生成模块的样板
;生成于 2026年03月14日 星期六 01:37:47

[Info]
Name = 字符串列表
DescShort = 字符串列表
DescLong = 字符串列表



[Register]
Rules#**** = StringList


Rules#[****]
SkipExport#Var=true
SkipTitle#Var=true
#StrEntry.=


