;INI织网者 V1.0.8
;这是一个生成模块的样板
;生成于 2026年03月14日 星期六 01:37:47

[Info]
Name = 顺序集线器
DescShort = 顺序集线器
DescLong = 一个集线器，但是展开了右侧的节点，直观展现连接的顺序。



[Register]
Rules#**** = StringList


Rules#[****]
SkipExport#Var=true
SkipTitle#Var=true
WidthRatio#Var=0.5
#MultColl.=
#MultColl1=

