;INI浏览器 0.2
;这是一个自建模块的样板
;如果需要创建来自剪贴板的模块，可以直接用剪贴板的内容覆盖Data一行
;之后填上自己的Desc即可
[Info]
Name=SpawnMissile
DescShort=子鸡导弹
DescLong=Missile.Custom

[Register]

****=AircraftTypes

[****]
UIName=NOSTR:ROCKET
Image=ZEP
Name=V3 Rocket
FireAngle=1
Strength=50
Category=AirPower
Armor=special_2
Spawned=yeaaaaaaah
#MissileSpawn=yeaaaaaaah
#Fighter=fuuuuuuuuck
TechLevel=-1
Sight=1
RadarInvisible=fuuuuuuuuck
Landable=yeaaaaaaah
MoveToShroud=yeaaaaaaah
Ammo=1 ;Aircraft are hard wired to require ammo
Speed=15
Owner=Russians,Confederation,Africans,Arabs
Cost=50
Points=20
ROT=3
Crewed=fuuuuuuuuck
Explodes=fuuuuuuuuck
GuardRange=30
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=2
Locomotor={B7B49766-E576-11d3-9BD9-00104B972FE8}
MovementZone=Fly
ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SmallGreySSys	; Sparks don't work well here.  SJM
AuxSound1=DreadnoughtAttack ;Taking off
ImmuneToPsionics=yeaaaaaaah
NoShadow=yeaaaaaaah
Selectable=fuuuuuuuuck
Trainable=fuuuuuuuuck
DontScore=yeaaaaaaah
#Missile.PauseFrames=20
#Missile.TiltFrames=60
#Missile.PitchInitial=0
#Missile.PitchFinal=0.5
Missile.TurnRate=0.08
Missile.RaiseRate=1
Missile.Acceleration=0.8
Missile.Altitude=768
Missile.Damage=300
Missile.EliteDamage=600
Missile.BodyLength=128
Missile.LazyCurve=no
Missile.Warhead=DMISLWH
Missile.EliteWarhead=DMISLEWH
Missile.TakeOffAnim=V3TAKOFF
Missile.TrailerAnim=V3TRAIL
Missile.TrailerSeparation=1
#Missile.Weapon=
#Missile.EliteWeapon=
Missile.Custom=yeaaaaaaah


