[Info]
Name=初始载荷（运兵车）TechnoType
DescShort=初始载荷（运兵车）TechnoType
DescLong=在命令与征服将军中中国的运兵车出厂时自带一个红卫兵，现在这个功能被加入了ARES豪华午餐。 如果是建筑，必须带有CanBeOccupied=yes或者InfantryAbsorb=yes设置，不然将不支持初始载荷逻辑。建筑只支持步兵载荷。 初始载荷不能超过建筑的MaxNumberOccupants或者载具的Passengers，并且要确保Size和SizeLimit没问题。 步兵不能用这逻辑。
[Register]
****=FlagPack
[****]
#InitialPayload=
#Passengers=
#SizeLimit=114514
#OpenTopped=yes

