[Info]
Name=Arcing弹跳
DescShort=Bounce
DescLong=(Arcing专用)模块：抛射体弹跳，状态类型 —— AE生效期间，Arcing类型抛射体在爆炸后会产生一个新的抛射体继续往前弹跳，碰撞地面会强制爆炸，撞到悬崖会反弹

[Register]
****=Bounce

[****]

#Duration=3
HoldDuration=yeaaaaaaah

ResetDurationOnReapply=yeaaaaaaah
AttachOnceInTechnoType=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck

Bounce.Chance=1
Bounce.Elasticity=0.5 ;弹性系数
Bounce.Limit=128 ;抛射体飞行的距离，两点的直线距离，乘以弹性系数后，至少要大于这个限制距离，才可以发生弹跳
Bounce.Times=-1 ;最多发生几次弹跳
Bounce.ExplodeOnHit=yeaaaaaaah ;抛射体命中后是否对落点造成伤害再弹起
Bounce.ExpireAnim= ;抛射体命中时播放的动画
Bounce.Weapon= ;发生弹跳后，弹起的是另一个武器，弹跳次数也衰减会传递给新抛射体，需注意Times的设置
; 对象影响过滤器专属设置
Bounce.OnWater=yeaaaaaaah ;打水漂，设置以下地形相关内容后无效
Bounce.OnLands= ;只允许在这种地形上弹起，水面上的桥将判定为Road而不是Water，Clear\Road\Water\Rock\Wall\Tiberium\Beach\Rough\Ice\Railroad\Tunnel\Weeds
Bounce.OnTiles= ;只允许在这种地块上弹起，Tunnel\Water\Blank\Ramp\Cliff\Shore\Wet\MiscPave\Pave\DirtRoad\PavedRoad\PavedRoadEnd\PavedRoadSlope\Median\Bridge\WoodBridge\ClearToSandLAT\Green\NotWater\DestroyableCliff
Bounce.StopOnBuilding=fuuuuuuuuck ;击中建筑后不会弹起
Bounce.ReboundOnBuilding=yeaaaaaaah ;击中建筑后反弹
Bounce.StopOnInfantry=fuuuuuuuuck ;击中步兵后不会弹起
Bounce.ReboundOnInfantry=yeaaaaaaah ;击中步兵后反弹
Bounce.StopOnUnit=fuuuuuuuuck ;击中载具后不会弹起
Bounce.ReboundOnUnit=yeaaaaaaah ;击中载具后反弹
