[Info]
Name=ROT类专用ECM
DescShort=ECM
DescLong= (Missile专用)模块：ECM电子对抗，状态类型 —— AE生效期间，发射电磁脉冲让抛射体随机选取原目标附近的一个小可爱作为新目标

[Register]
****=ECM

[****]

#Duration=3
HoldDuration=yeaaaaaaah

ResetDurationOnReapply=yeaaaaaaah
AttachOnceInTechnoType=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck

ECM.Chance=100% ;干扰成功率，大于0%启用
ECM.Rate=15 ;导弹间隔多少帧改一次目标
ECM.TriggeredTimes=1 ;导弹在持续时间内更改多少次目标，不成功也扣除一次
ECM.LockDuration=0 ;干扰生效后，多久不会再收到干扰
#ECM.Feedback=fuuuuuuuuck ;忽悠炮，艹他，导弹不搜索新目标，而是返回去干发射者，发射者不存在，原地爆炸
#ECM.ToTechnoChance=0% ;干扰生效后，导弹选择单位而不是地面的概率
ECM.ForceRetarget=fuuuuuuuuck ;干扰生效后，导弹一定重选一个不同于原来目标的目标，如果范围内没有其他目标，就砸地上
ECM.NoOwner=fuuuuuuuuck ;干扰生效后，导弹变成无主状态，可以伤害发射者，击杀目标也不会给发射者经验
; 新目标选择范围的专属设置
#ECM.Around=Source ;干扰生效后，导弹选择目标的圆心位置，Source/Target/Self/Shooter，Source=AE来源周围，Target=前往的目标周围，Self=自身周围，Shooter=发射者的周围，如果指定的点无效，那么就在自身周围附近找个点扎
ECM.RangeMin=0 ;干扰生效后，导弹选择目标的最小范围，单位格
ECM.RangeMax=1 ;干扰生效后，导弹选择目标的最大范围，单位格
ECM.FullAirspace=fuuuuuuuuck ;测算距离无视高度，即圆柱形范围检查
; 新目标选择对象影响过滤器专属设置
ECM.AffectTypes= ;类型过滤，可影响的单位，如果设置，则只转向清单中的单位
ECM.NotAffectTypes= ;类型过滤，不可影响的单位，如果设置，则不转向列表中的单位，优先级更高
; 新目标选择对象影响单位设置
ECM.AffectInfantry=yeaaaaaaah ;类型过滤，影响步兵
ECM.AffectUnit=yeaaaaaaah ;类型过滤，影响载具
ECM.AffectAircraft=yeaaaaaaah ;类型过滤，影响飞机
; 新目标选择影响特定对象
ECM.AffectInAir=yeaaaaaaah ;影响在空中的单位
ECM.NotAffectMarks= ;不影响带有这些标记的对象
ECM.OnlyAffectMarks= ;只影响带有这些标记的对象
; 新目标选择影响对象敌我识别专属设置
ECM.AffectsOwner=yeaaaaaaah ;是否影响同阵营的
ECM.AffectsAllies=yeaaaaaaah ;是否影响友军
ECM.AffectsEnemies=yeaaaaaaah ;是否影响敌人
ECM.AffectsCivilian=yeaaaaaaah ;是否影响中立目标
