
;INI织网者 V1.0.7
;这是一个生成模块的样板
;生成于 2026年02月23日 星期一 20:52:03

[Info]
Name = ZepBomb
DescShort = ZepBomb
DescLong = 飞艇炸弹
ParamDescShort = 
ParamDescLong = 



[Register]
Rules#****0 = WeaponTypes
Rules#****1 = ProjectileTypes
Rules#****2 = Warheads


Rules#[****0]
ImportDeltaX = -7.932827
ImportDeltaY = -1.025117
_InitialSecName#Var = ****0
_Local_Category#Var = WeaponTypes
Damage = 250
Burst = 1
ROF = 50
Range = 1.5
CellRangefinding = yeaaaaaaah
#Projectile = ****1
Speed = 20
#Warhead = ****2
Report = KirovAttack
OmniFire = yeaaaaaaah


Rules#[****1]
ImportDeltaX = 7.629673
ImportDeltaY = -0.775117
_InitialSecName#Var = ****1
_Local_Category#Var = ProjectileTypes
Image = ZBOMB
Arm = 10
Shadow = fuuuuuuuuck
Acceleration = 1
Vertical = yeaaaaaaah
DetonationAltitude = 20000


Rules#[****2]
ImportDeltaX = 7.942173
ImportDeltaY = 2.787383
_InitialSecName#Var = ****2
_Local_Category#Var = Warheads
CellSpread = 2
PercentAtMax = .5
Wall = yeaaaaaaah
Wood = yeaaaaaaah
Verses = 100%,100%,100%,70%,35%,35%,85%,75%,50%,100%,100%
Conventional = yeaaaaaaah
Rocker = yeaaaaaaah
InfDeath = 2
AnimList = XGRYSML1,XGRYSML2,EXPLOSML,XGRYMED1,XGRYMED2,EXPLOMED,EXPLOLRG,TWLT070
Tiberium = yeaaaaaaah
Sparky = fuuuuuuuuck
Bright = yeaaaaaaah
ProneDamage = 70%


