;INI浏览器 0.2
;默认的素材模块模板
[Info]
Name=DefaultEVA
DescShort=DefaultEVA
DescLong=DefaultEVA

[Register]
Eva#****=DialogList


Eva#[****]
Text=我可不知道你打算把哪个声音给谁，所以全放进Russian了
Russian=
Allied=
Yuri=
Type= QUEUE
Priority=LOW

