[Info]
Name=Team Types
DescShort=作战小队
DescLong=
[Register]
AI#****=TeamTypes


AI#[****]
Name=
VeteranLevel=1
MindControlDecision=0
Loadable=no
Full=no
Annoyance=no
GuardSlower=no
House=<none>
#Recruiter=no
Autocreate=yes
Prebuild=no
Reinforce=no
Droppod=no
UseTransportOrigin=no
Whiner=no
LooseRecruit=no
Aggressive=yes
Suicide=yes
Priority=5
Max=1
TechLevel=0
Group=-1
OnTransOnly=no
AvoidThreats=no
IonImmune=no
TransportsReturnOnUnload=no
#AreTeamMembersRecruitable=no
#IsBaseDefense=no
OnlyTargetHouseEnemy=no
#Script=
#TaskForce=


