[Info]
Name=失活状态
DescShort=Freeze
DescLong=停止运动, 状态类型 —— AE生效期间，单位无法行动，硬在原地，像中了EMP一样

[Register]
****=Freeze

[****]
Freeze.Enable=yeaaaaaaah
Freeze.AffectWho=ALL ;作用于谁，ALL\MASTER\STAND
#Duration=3
HoldDuration=fuuuuuuuuck

ResetDurationOnReapply=yeaaaaaaah
AttachOnceInTechnoType=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck
