[Info]
Name=变身
DescShort=Transform
DescLong=AE生效期间，更改附着对象的单位类型，只允许同类之间进行转换，如动员兵变身磁暴步兵，无法对抛射体生效。

[Register]
****=Transform

[****]
Transform.Type=
#Duration=400
HoldDuration=fuuuuuuuuck

ResetDurationOnReapply=yeaaaaaaah
AttachOnceInTechnoType=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck
