[Info]
Name=拿钱说话
DescShort=NoMoneyNoTalk
DescLong=需要金钱才能发射武器

[Register]
****=NoMoneyNoTalk

[****]

#Duration=3
HoldDuration=fuuuuuuuuck

ResetDurationOnReapply=yeaaaaaaah
AttachOnceInTechnoType=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck
#NoMoneyNoTalk=1000
NoMoneyNoTalk.AffectWho=ALL
