[Info]
Name=武器覆盖
DescShort=OverrideWeapon
DescLong=AE生效期间，附着的对象或其替身在使用武器对目标进行攻击的时候，强制选出1个来替换将要发射的武器，精英武器不会复用普通武器

[Register]
****=OverrideWeapon

[****]

#Duration=3
HoldDuration=fuuuuuuuuck

ResetDurationOnReapply=yeaaaaaaah
AttachOnceInTechnoType=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck

OverrideWeapon.Types=
OverrideWeapon.Weights=1
OverrideWeapon.Index=-1
OverrideWeapon.EliteTypes=
OverrideWeapon.EliteWeights=1
OverrideWeapon.EliteIndex=-1
OverrideWeapon.Chance=100%
OverrideWeapon.EliteChance=100%
OverrideWeapon.UseToDeathWeapon=fuuuuuuuuck
OverrideWeapon.AffectWho=ALL
