[Info]
Name=死亡动画
DescShort=DestroyAnim
DescLong=AE生效期间，单位死亡时，不播放原先的死亡动画，改为播放指定的死亡动画。这些语句还可以写弹头上或单位身上。

[Register]
****=DestroyAnim

[****]

#Duration=3
HoldDuration=fuuuuuuuuck

ResetDurationOnReapply=yeaaaaaaah
AttachOnceInTechnoType=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck

DestroyAnim.Types=
DestroyAnim.Random=fuuuuuuuuck ;随机播放死亡动画，非8的倍数也随机
DestroyAnim.PlayInAir=fuuuuuuuuck ;死亡动画在空中也播放
DestroyAnim.Owner=Invoker ;死亡动画和残骸的归属，Invoker|Killer|Neutral
; 刷出实体残骸，残骸优先级比死亡动画高，残骸无法在空中生成，在空中会转为播放死亡动画
DestroyAnim.WreckType=HTNK ;死亡时在原位置刷出另一个实体单位，作为残骸存在，残骸默认任务为Sleep，设置时覆盖动画设置
DestroyAnim.WreckMission=Sleep ;死亡残骸的任务，None\Guard\AreaGuard\Hunt\Sleep
; 死亡动画影响过滤器专属设置
DestroyAnim.AffectTypes= ;类型过滤，可影响的单位，如果设置，则只有列表中的单位死亡时替换死亡动画
DestroyAnim.NotAffectTypes= ;类型过滤，不可影响的单位，如果设置，则列表中的单位死亡时不会替换死亡动画
; 死亡动画影响单位设置
DestroyAnim.AffectInfantry=yeaaaaaaah ;类型过滤，替换步兵
DestroyAnim.AffectUnit=yeaaaaaaah ;类型过滤，替换载具
DestroyAnim.AffectWho=MASTER ;作用于谁，ALL\MASTER\STAND