[Info]
Name=黑洞
DescShort=BlackHole
DescLong=（不稳定，易崩） 模块：黑洞, 状态类型 —— AE生效期间，附着对象会间歇性的吸引附近的抛射体和单位

[Register]
****=BlackHole

[****]

#Duration=3
HoldDuration=fuuuuuuuuck

ResetDurationOnReapply=yeaaaaaaah
AttachOnceInTechnoType=yeaaaaaaah
PenetratesIronCurtain=yeaaaaaaah
DiscardOnTransform=fuuuuuuuuck

#BlackHole.Range=-1
BlackHole.FullAirspace=yeaaaaaaah ;测算距离无视高度，即圆柱形范围检查
BlackHole.EliteRange=-1
BlackHole.EliteFullAirspace=yeaaaaaaah ;测算距离无视高度，即圆柱形范围检查
BlackHole.Rate=15 ;扫描的频率，间隔多少帧扫描一次，越大越慢
BlackHole.EliteRate=15 ;精英级扫描的频率，间隔多少帧扫描一次，越大越慢
BlackHole.Offset=0,0,0 ;黑洞位置的偏移，FLH
BlackHole.IsOnTurret=yeaaaaaaah ;黑洞绑定在炮塔
BlackHole.TriggeredTimes=-1 ;黑洞触发的次数，次数用完立刻强制结束效果
#BlackHole.DontScan=yeaaaaaaah ;不主动扫描，在仅使用弹头添加受害者时关闭区域扫描节省资源
; 黑洞的质量和拉取速度
BlackHole.Weight=99999 ;黑洞的质量，高于这个质量的单位不受影响，多个黑洞拉扯，质量高的获得控制权，黑洞的质量为0时，抓取时不计算目标质量，以恒定速度抓取
BlackHole.CaptureFromSameWeight=yeaaaaaaah ;从相同质量的黑洞手里抢东西
#BlackHole.CaptureFromWarhead=yeaaaaaaah ;通过弹头添加受害者，弹头需要 Capturer=yeaaaaaaah
BlackHole.CaptureSpeed=30 ;黑洞拉取时单位的Weight=1时的基本速度，v=F/mt
BlackHole.CaptureIgnoreWeight=yeaaaaaaah ;黑洞拉去时无视单位的质量，使用恒定速度
BlackHole.AllowCrawl=yeaaaaaaah ;在拉扯时步兵单位扑街
BlackHole.AllowRotateUnit=yeaaaaaaah ;在拉扯时调整单位的朝向
#BlackHole.AllowPassBuilding=yeaaaaaaah ;是否允许穿越障碍
; 黑洞影响伤害设置
BlackHole.Damage=0 ;黑洞持续过程中产生伤害
BlackHole.Damage.Delay=0 ;黑洞产生伤害的频率
BlackHole.Damage.Warhead=
#BlackHole.AllowFallingDestroy=fuuuuuuuuck ;允许被黑洞吸起的单位超过一定高度时直接摔死
#BlackHole.FallingDestroyHeight=208 ;坠落高度，1格=104，2格=飞行器
BlackHole.AllowDamageTechno=yeaaaaaaah ;允许伤害被捕获的单位
BlackHole.AllowDamageBullet=fuuuuuuuuck ;允许伤害被捕获的抛射体
BlackHole.ClearTarget=yeaaaaaaah ;强令被捕获的对象失去目标
BlackHole.ChangeTarget=fuuuuuuuuck ;强令被捕获的对象目标设置为黑洞
BlackHole.OutOfControl=yeaaaaaaah ;被捕获的对象无法控制，无法行动
; 黑洞影响过滤器专属设置
BlackHole.AffectBlackHole=yeaaaaaaah ;能否捕获另一个黑洞
BlackHole.AffectTypes= ;类型过滤，可影响的单位，如果设置，则只可以影响列表中的单位
BlackHole.NotAffectTypes= ;类型过滤，不可影响的单位，如果设置，则列表中的单位不被吸引，优先级更高
; 黑洞影响单位设置
BlackHole.AffectTechno=fuuuuuuuuck ;类型过滤，是否可以影响范围的单位（注意Affect没有s）
BlackHole.AffectBuilding=yeaaaaaaah ;类型过滤，影响范围内的建筑，建筑不能被拔起，但是可以收到伤害
BlackHole.AffectInfantry=yeaaaaaaah ;类型过滤，影响范围内的步兵
BlackHole.AffectUnit=yeaaaaaaah ;类型过滤，影响范围内的载具
BlackHole.AffectAircraft=yeaaaaaaah ;类型过滤，影响范围内的飞机
; 黑洞影响抛射体设置
BlackHole.AffectBullet=yeaaaaaaah ;类型过滤，影响范围内的抛射体（注意Affect没有s）
BlackHole.AffectMissile=yeaaaaaaah ;类型过滤，影响ROT>0的抛射体
BlackHole.AffectTorpedo=yeaaaaaaah ;类型过滤，影响Level=yeaaaaaaah的抛射体
BlackHole.AffectCannon=yeaaaaaaah ;类型过滤，影响Arcing=yeaaaaaaah的抛射体
BlackHole.AffectBomb=yeaaaaaaah ;类型过滤，影响Vertical=yeaaaaaaah的抛射体
; 影响特定对象
BlackHole.AffectInAir=yeaaaaaaah ;影响在空中的单位
BlackHole.NotAffectMarks= ;不影响带有这些标记的对象
BlackHole.OnlyAffectMarks= ;只影响带有这些标记的对象
; 黑洞敌我识别专属设置
BlackHole.AffectsOwner=fuuuuuuuuck ;敌我识别，影响发射者同阵营（注意Affects有s）
BlackHole.AffectsAllies=fuuuuuuuuck ;敌我识别，影响友军（注意Affects有s）
BlackHole.AffectsEnemies=yeaaaaaaah ;敌我识别，影响敌人（注意Affects有s）
BlackHole.AffectsCivilian=yeaaaaaaah ;敌我识别，影响平民（注意Affects有s）
BlackHole.DeactiveWhenCivilian=fuuuuuuuuck ;启用时，当所属是平民时，或者被狙掉了驾驶员，不会激活效果
BlackHole.AffectWho=MASTER ;谁是黑洞，ALL\MASTER\STAND